version: '3.8'
services:
  funnylittlewebsite:
    image: funnylittlewebsite:latest
    build:
      context: .
      dockerfile: FunnyLittleWebsite/Dockerfile
    ports:
      - "5252:443"  # Map your external port to the container's HTTPS port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}  # Use environment variable
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/certificate.pfx
    volumes:
      - myapp_certs:/certs  # Mount the volume containing the certificate
      - .:/app  # Mount the source code for live changes (optional in production)
    networks:
      - webnet

networks:
  webnet:
volumes:
  myapp_certs:  # Define the volume to be used for storing certificates
