name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup SSH Key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > $HOME/.ssh/github_actions_rsa
          chmod 600 $HOME/.ssh/github_actions_rsa
          
      - name: Setup Known Hosts
        run: |
          ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> $HOME/.ssh/known_hosts
          
      - name: Test SSH Connection
        run: ssh -vT -i $HOME/.ssh/github_actions_rsa server1admin@${{ secrets.SERVER_IP }}
        
      - name: Upload Docker Image to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: server1admin
          key: $HOME/.ssh/github_actions_rsa
          port: 22
          source: "funnylittlewebsite.tar.gz"
          target: "/home/server1admin/"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: server1admin
          key: $HOME/.ssh/github_actions_rsa
          port: 22
          script: |
            docker load < funnylittlewebsite.tar.gz
            docker stop funnylittlewebsite || true
            docker rm funnylittlewebsite || true
            docker run -d --name funnylittlewebsite -p 80:80 funnylittlewebsite:latest

