name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build ./FunnyLittleWebsite -t funnylittlewebsite:latest

      - name: Save Docker Image
        run: docker save funnylittlewebsite:latest | gzip > funnylittlewebsite.tar.gz

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -vT -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no server1admin@${{ secrets.SERVER_IP }}

      - name: Upload Docker Image to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: server1admin
          key: ${{ github.workspace }}/.ssh/id_rsa
          port: 22
          source: "funnylittlewebsite.tar.gz"
          target: "/home/server1admin/"
          rm: true
          debug: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: server1admin
          key: ${{ github.workspace }}/.ssh/id_rsa
          port: 22
          script: |
            docker load < /home/server1admin/funnylittlewebsite.tar.gz
            docker stop funnylittlewebsite || true
            docker rm funnylittlewebsite || true
            docker run -d --name funnylittlewebsite -p 80:80 funnylittlewebsite:latest
