name: Deploy to Server

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: funnylittlewebsite:latest
  SSH_KEY_PATH: ${{ github.workspace }}/.ssh/github_actions_rsa
  DEPLOYMENT_PATH: /home/server1admin/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build ./FunnyLittleWebsite -t $DOCKER_IMAGE_NAME

      - name: Save Docker Image
        run: docker save $DOCKER_IMAGE_NAME | gzip > funnylittlewebsite.tar.gz

      - name: Setup SSH Key and Known Hosts
        run: |
          mkdir -p ${{ github.workspace }}/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > $SSH_KEY_PATH
          chmod 600 $SSH_KEY_PATH
          ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> ${{ github.workspace }}/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -vT -i $SSH_KEY_PATH -o StrictHostKeyChecking=no server1admin@${{ secrets.SERVER_IP }}

      - name: Upload Docker Image to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: server1admin
          key: $SSH_KEY_PATH
          port: 22
          source: "funnylittlewebsite.tar.gz"
          target: $DEPLOYMENT_PATH
          rm: true
          debug: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: server1admin
          key: $SSH_KEY_PATH
          port: 22
          script: |
            docker load < ${DEPLOYMENT_PATH}funnylittlewebsite.tar.gz
            docker stop funnylittlewebsite || true
            docker rm funnylittlewebsite || true
            docker run -d --name funnylittlewebsite -p 80:80 $DOCKER_IMAGE_NAME
