name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build ./FunnyLittleWebsite -t funnylittlewebsite:latest

      - name: Save Docker Image
        run: docker save funnylittlewebsite:latest | gzip > funnylittlewebsite.tar.gz

      - name: Setup SSH Directory and Key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> $HOME/.ssh/known_hosts


      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: server1admin
          key: ${{ runner.home }}/.ssh/id_rsa
          port: 22
          script: |
            set -e
            docker load < /home/server1admin/funnylittlewebsite.tar.gz
            docker stop funnylittlewebsite || true
            docker rm funnylittlewebsite || true
            docker run -d --name funnylittlewebsite -p 80:80 funnylittlewebsite:latest
